spring:
  profiles:
    active: local
---
server:
  port: 8081

spring:
  profiles: local
  application:
    name: app-caller
  datasource:
    # url: jdbc:mariadb://localhost:3306/demo
    # driverClassName: org.mariadb.jdbc.Driver
    # username: scott
    # password: tiger
    url: jdbc:mysql://10.88.11.151:3306/btsdb
    driverClassName: com.mysql.cj.jdbc.Driver
    username: bts
    password: btsuser
    
mybatis:
  configuration:
    multiple-result-sets-enabled: false
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true    
    jdbc-type-for-null: varchar
    default-fetch-size: 500
  mapper-locations:
  - classpath:mybatis/mapper/*.xml
              
logging:  
  pattern:
    console: "%-5level %d{HH:mm:ss.SSS} %logger[%method:%line] - %msg%n"
  level:
    cj: DEBUG
    
feign:
  basePackages: cj.bts.ord.httpclient   
  delivery:
    url: http://localhost:8082
        
opentracing:      
  jaeger:
    service-name: ${spring.application.name} # jaeger service Name
    probabilistic-sampler:
      sampling-rate: 1.0
    udp-sender:
      host: localhost # jaeger server id
      port: 6831 # jaeger udp Port 