spring:
  profiles:
    active: local
---
server:
  port: 9999

spring:
  config:
    activate:
      on-profile: local
  application:
    name: message-relay
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    showSql: true
    generate-ddl: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
            
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    cj: DEBUG
