spring:
  profiles:
    active: local
---
server:
  port: 8888

spring:
  config:
    activate:
      on-profile: local
  application:
    name: message-creator
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    showSql: false
    generate-ddl: true
            
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    cj: ERROR
