
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/temp
    username: scott
    password: tiger
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 3
      maximum-pool-size: 3
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
    jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      properties:
        hibernate:
          format_sql: true
          implicit_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
          physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          hbm2ddl.auto: update
      open-in-view: false
      show-sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
