spring:
  profiles:
    active: local
---
server:
  port: 8080

spring:
  profiles: local
  application:
    name: example-cj
  datasource:
    url: jdbc:mariadb://localhost:3306/demo
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  add-messages: classpath:/messages/abc
          
logging:
  pattern:
    console: "%-5level %d{HH:mm:ss.SSS} %logger[%method:%line] - %msg %mdc%n"
  level:
    cj: DEBUG

feign:
  basePackages: yongs.temp.httpclient
  product:
    url: http://localhost:8083
    
springdoc:
  swagger-ui:
    path: ${spring.application.name}.html
  version: v1 
  
opentracing:      
  jaeger:
    service-name: ${spring.application.name} # jaeger service Name
    probabilistic-sampler:
      sampling-rate: 1.0
    udp-sender:
      host: localhost # jaeger server id
      port: 6831 # jaeger udp Port 