version: '3'
services:
 
  redis-master:
     image: redis:5.0-alpine   # image 옵션으로 redis공식이미지를 기반으로 생성합니다.
     build:
       context: ..             # build file에 대한 context를 지정
       dockerfile: Dockerfile  #dockerfile명을 지정합니다. (Default는 "Dockerfile" 파일명을 가진 파일을 실행합니다.)
     network_mode: "host"      # Image가 Container가 되었을때 network모드를 host모드로 설정합니다 (docker0 인터페이스를 사용하지 않고 Host OS의 eth0 인터페이스 사용)
     environment:              # Container 내부에서 사용 할 환경변수를 설정합니다.
      - REQUIREPASS=password1234
      - CLIENTPORT=6379
      - CLIENTHOST=192.168.137.101
      - MASTERHOST=
      - MASTERPORT=
     volumes:  # Host OS의 디렉터리와 Container내의 디렉터리와 연동합니다.
      - "../redis-data/redis1:/data"
     restart: always
 
  redis-slave1:
     image: redis:5.0-alpine
     build:
       context: ..
       dockerfile: Dockerfile
     network_mode: "host"
     environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6380
      - MASTERPORT=6379
      - CLIENTHOST=192.168.137.101
      - MASTERHOST=192.168.137.101
     volumes:
      - "../redis-data/redis2:/data"
     restart: always
 
  redis-slave2:
     image: redis:5.0-alpine
     build:
       context: ..
       dockerfile: Dockerfile
     network_mode: "host"
     environment:
      - REQUIREPASS=password1234
      - CLIENTPORT=6381
      - MASTERPORT=6379
      - CLIENTHOST=192.168.137.101
      - MASTERHOST=192.168.137.101 
     volumes:
      - "../redis-data/redis3:/data"
     restart: always