spring:
  profiles:
    active: local
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: local
  application:
    name: temp-app
  datasource:
    url: jdbc:mariadb://localhost:3306/temp
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    showSql: true
    generate-ddl: true
      
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - [%-5level] - %msg%n"
  level:
    com:
      example: DEBUG
